[package]
name = "chap09"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
libc = "0.2"
plotters = "0.3"
serde_json = "1.0"
num_cpus = "1.0"
